//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lawyers.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Procedure
    {
        public int ProcedureId { get; set; }
        public string Topic { get; set; }
        public string Description { get; set; }
        public int LawyerId { get; set; }
        public int ClientId { get; set; }
        public int StateId { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Lawyer Lawyer { get; set; }
        public virtual State State { get; set; }
    }
}
